// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package setupb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SetuServiceClient is the client API for SetuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SetuServiceClient interface {
	GetInventory(ctx context.Context, in *InventoryReq, opts ...grpc.CallOption) (*InventoryResp, error)
	Fetch(ctx context.Context, in *FetchReq, opts ...grpc.CallOption) (*FetchResp, error)
	GetSetuById(ctx context.Context, in *SetuReq, opts ...grpc.CallOption) (SetuService_GetSetuByIdClient, error)
	Random(ctx context.Context, in *RandomReq, opts ...grpc.CallOption) (SetuService_RandomClient, error)
	Count(ctx context.Context, in *CountReq, opts ...grpc.CallOption) (*CountResp, error)
}

type setuServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSetuServiceClient(cc grpc.ClientConnInterface) SetuServiceClient {
	return &setuServiceClient{cc}
}

func (c *setuServiceClient) GetInventory(ctx context.Context, in *InventoryReq, opts ...grpc.CallOption) (*InventoryResp, error) {
	out := new(InventoryResp)
	err := c.cc.Invoke(ctx, "/setu.SetuService/GetInventory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *setuServiceClient) Fetch(ctx context.Context, in *FetchReq, opts ...grpc.CallOption) (*FetchResp, error) {
	out := new(FetchResp)
	err := c.cc.Invoke(ctx, "/setu.SetuService/Fetch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *setuServiceClient) GetSetuById(ctx context.Context, in *SetuReq, opts ...grpc.CallOption) (SetuService_GetSetuByIdClient, error) {
	stream, err := c.cc.NewStream(ctx, &SetuService_ServiceDesc.Streams[0], "/setu.SetuService/GetSetuById", opts...)
	if err != nil {
		return nil, err
	}
	x := &setuServiceGetSetuByIdClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SetuService_GetSetuByIdClient interface {
	Recv() (*SetuResp, error)
	grpc.ClientStream
}

type setuServiceGetSetuByIdClient struct {
	grpc.ClientStream
}

func (x *setuServiceGetSetuByIdClient) Recv() (*SetuResp, error) {
	m := new(SetuResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *setuServiceClient) Random(ctx context.Context, in *RandomReq, opts ...grpc.CallOption) (SetuService_RandomClient, error) {
	stream, err := c.cc.NewStream(ctx, &SetuService_ServiceDesc.Streams[1], "/setu.SetuService/Random", opts...)
	if err != nil {
		return nil, err
	}
	x := &setuServiceRandomClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SetuService_RandomClient interface {
	Recv() (*SetuResp, error)
	grpc.ClientStream
}

type setuServiceRandomClient struct {
	grpc.ClientStream
}

func (x *setuServiceRandomClient) Recv() (*SetuResp, error) {
	m := new(SetuResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *setuServiceClient) Count(ctx context.Context, in *CountReq, opts ...grpc.CallOption) (*CountResp, error) {
	out := new(CountResp)
	err := c.cc.Invoke(ctx, "/setu.SetuService/Count", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SetuServiceServer is the server API for SetuService service.
// All implementations must embed UnimplementedSetuServiceServer
// for forward compatibility
type SetuServiceServer interface {
	GetInventory(context.Context, *InventoryReq) (*InventoryResp, error)
	Fetch(context.Context, *FetchReq) (*FetchResp, error)
	GetSetuById(*SetuReq, SetuService_GetSetuByIdServer) error
	Random(*RandomReq, SetuService_RandomServer) error
	Count(context.Context, *CountReq) (*CountResp, error)
	mustEmbedUnimplementedSetuServiceServer()
}

// UnimplementedSetuServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSetuServiceServer struct {
}

func (UnimplementedSetuServiceServer) GetInventory(context.Context, *InventoryReq) (*InventoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInventory not implemented")
}
func (UnimplementedSetuServiceServer) Fetch(context.Context, *FetchReq) (*FetchResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedSetuServiceServer) GetSetuById(*SetuReq, SetuService_GetSetuByIdServer) error {
	return status.Errorf(codes.Unimplemented, "method GetSetuById not implemented")
}
func (UnimplementedSetuServiceServer) Random(*RandomReq, SetuService_RandomServer) error {
	return status.Errorf(codes.Unimplemented, "method Random not implemented")
}
func (UnimplementedSetuServiceServer) Count(context.Context, *CountReq) (*CountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Count not implemented")
}
func (UnimplementedSetuServiceServer) mustEmbedUnimplementedSetuServiceServer() {}

// UnsafeSetuServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SetuServiceServer will
// result in compilation errors.
type UnsafeSetuServiceServer interface {
	mustEmbedUnimplementedSetuServiceServer()
}

func RegisterSetuServiceServer(s grpc.ServiceRegistrar, srv SetuServiceServer) {
	s.RegisterService(&SetuService_ServiceDesc, srv)
}

func _SetuService_GetInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InventoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetuServiceServer).GetInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/setu.SetuService/GetInventory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetuServiceServer).GetInventory(ctx, req.(*InventoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SetuService_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetuServiceServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/setu.SetuService/Fetch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetuServiceServer).Fetch(ctx, req.(*FetchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SetuService_GetSetuById_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SetuReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SetuServiceServer).GetSetuById(m, &setuServiceGetSetuByIdServer{stream})
}

type SetuService_GetSetuByIdServer interface {
	Send(*SetuResp) error
	grpc.ServerStream
}

type setuServiceGetSetuByIdServer struct {
	grpc.ServerStream
}

func (x *setuServiceGetSetuByIdServer) Send(m *SetuResp) error {
	return x.ServerStream.SendMsg(m)
}

func _SetuService_Random_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RandomReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SetuServiceServer).Random(m, &setuServiceRandomServer{stream})
}

type SetuService_RandomServer interface {
	Send(*SetuResp) error
	grpc.ServerStream
}

type setuServiceRandomServer struct {
	grpc.ServerStream
}

func (x *setuServiceRandomServer) Send(m *SetuResp) error {
	return x.ServerStream.SendMsg(m)
}

func _SetuService_Count_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetuServiceServer).Count(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/setu.SetuService/Count",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetuServiceServer).Count(ctx, req.(*CountReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SetuService_ServiceDesc is the grpc.ServiceDesc for SetuService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SetuService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "setu.SetuService",
	HandlerType: (*SetuServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInventory",
			Handler:    _SetuService_GetInventory_Handler,
		},
		{
			MethodName: "Fetch",
			Handler:    _SetuService_Fetch_Handler,
		},
		{
			MethodName: "Count",
			Handler:    _SetuService_Count_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSetuById",
			Handler:       _SetuService_GetSetuById_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Random",
			Handler:       _SetuService_Random_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "setu.proto",
}
